version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: server-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
  api-server:
    build:
      context: api-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      LOCALHOST: host.docker.internal

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
